import React, { useState, useMemo } from 'react';
import type { LayerMap, Severity, DisasterEvent } from './types';
import { AEGIS_DATA } from './data/mockData';
// @ts-ignore — liveData.ts is generated by aegis_pipeline.py --score
import { LIVE_DATA } from './data/liveData';
import { interpolateRisks } from './lib/timeUtils';

const DATA = (typeof LIVE_DATA !== 'undefined' ? LIVE_DATA : null) ?? AEGIS_DATA;
import { useClock } from './hooks/useClock';
import { useTimeline } from './hooks/useTimeline';
import { scrubToDaysOffset } from './components/timeline/Timeline';

import TopBar from './components/topbar/TopBar';
import WorldMap from './components/map/WorldMap';
import Timeline from './components/timeline/Timeline';
import SensorNetwork from './components/panels/SensorNetwork';
import ForecastChart from './components/panels/ForecastChart';
import EventGroup from './components/events/EventGroup';
import { ExpandIcon, DownloadIcon } from './components/icons';

const { metrics, timelineMarkers } = DATA;

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low'];

const LAYER_TOGGLES = [
  { k: 'wildfire' as const, label: 'FIRE',    color: '#FF6B35' },
  { k: 'cyclone'  as const, label: 'STORM',   color: '#00D4FF' },
  { k: 'flood'    as const, label: 'FLOOD',   color: '#3FA9FF' },
  { k: 'quake'    as const, label: 'QUAKE',   color: '#FFB547' },
  { k: 'drought'  as const, label: 'DROUGHT', color: '#C28A4A' },
];

const FILTER_BTNS = [
  { k: 'all',      label: 'ALL' },
  { k: 'critical', label: 'CRITICAL' },
  { k: 'high',     label: 'HIGH' },
  { k: 'medium',   label: 'MED' },
  { k: 'low',      label: 'LOW' },
];

export default function App() {
  const [selected,  setSelected]  = useState<string>('AEG-2407');
  const [expanded,  setExpanded]  = useState<string | null>('AEG-2407');
  const [filter,    setFilter]    = useState<string>('all');
  const [layers,    setLayers]    = useState<LayerMap>({
    wildfire: true, cyclone: true, flood: true, quake: true, drought: true,
  });

  function handleSelect(id: string) {
    if (selected === id) {
      setSelected('');
      setExpanded(null);
    } else {
      setSelected(id);
      setExpanded(id);
    }
  }

  const { now } = useClock();
  const { scrub, playing, setScrub, togglePlay } = useTimeline();
  // Use liveData.ts from pipeline (generated by aegis_pipeline.py --score)
  // EONET hook disabled — pipeline handles data freshness
  const events = useMemo(() => DATA.events, []);

  const daysBack = scrubToDaysOffset(scrub);
  const isReplay = Math.abs(scrub - 0.5) > 0.03;

  const interpolatedRisks = useMemo(
    () => interpolateRisks(events, daysBack),
    [events, daysBack],
  );

  const filteredEvents = useMemo(() => {
    // All events span dA=7→-7 continuously. Just dedup by closest snapshot to daysBack.
    const seen = new Map<string, DisasterEvent>();
    for (const ev of events) {
      const existing = seen.get(ev.id);
      if (!existing ||
          Math.abs(ev.detectedDaysAgo - daysBack) < Math.abs(existing.detectedDaysAgo - daysBack)) {
        seen.set(ev.id, ev);
      }
    }
    const deduped = Array.from(seen.values());

    if (filter === 'all') return deduped;
    return deduped.filter(e => e.severity === filter || e.kind === filter);
  }, [filter, daysBack, events]);

  const groupedEvents = useMemo(
    () => SEVERITY_ORDER.map(sev => ({
      severity: sev,
      events: [...filteredEvents.filter(e => e.severity === sev)].sort((a, b) => b.risk - a.risk),
    })),
    [filteredEvents],
  );

  const mapEvents = useMemo(() => {
    // All events span dA=7→-7. Dedup by closest snapshot to daysBack.
    const seen = new Map<string, DisasterEvent>();
    for (const ev of events.filter(e => layers[e.kind])) {
      const existing = seen.get(ev.id);
      if (!existing ||
          Math.abs(ev.detectedDaysAgo - daysBack) < Math.abs(existing.detectedDaysAgo - daysBack)) {
        seen.set(ev.id, ev);
      }
    }
    const deduped = Array.from(seen.values());

    // Always include storms with paths (for trajectory animation)
    const storms = deduped.filter(e => e.kind === 'cyclone' && e.path);
    const others = deduped
      .filter(e => !(e.kind === 'cyclone' && e.path))
      .sort((a, b) => b.risk - a.risk)
      .slice(0, 30 - storms.length);
    return [...storms, ...others];
  }, [layers, events, daysBack]);

  return (
    <div className="app" data-screen-label="01 Mission Control">
      <div className="main">
        <TopBar metrics={metrics} now={now} nextPass={DATA.nextPass} />

        <div className="grid">
          <section className="col-center">
            <div className="map-wrap">
              <div className="map-header">
                <div className="map-header-left">
                  <div className="mh-title">
                    PLANETARY HAZARD MAP
                    {isReplay
                      ? <span className="mh-replay-badge">REPLAY MODE</span>
                      : <span className="mh-live-badge">LIVE</span>
                    }
                  </div>
                  <div className="mh-sub">NASA EONET · Open-Meteo · Models M1/M2/M2b/M2c</div>
                  <div className="map-watermark">DATA: NASA EONET API · Open-Meteo ERA5 · PREDICTFY ML ENGINE</div>
                </div>
                <div className="map-header-mid">
                  <div className="layer-toggles">
                    {LAYER_TOGGLES.map(l => (
                      <button
                        key={l.k}
                        className={`ltog ${layers[l.k] ? 'on' : ''}`}
                        onClick={() => setLayers(s => ({ ...s, [l.k]: !s[l.k] }))}
                        style={{ '--lc': l.color } as React.CSSProperties}
                      >
                        <span className="ltog-dot" />{l.label}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="map-header-right">
                  <button className="mh-icon" title="Expand"><ExpandIcon width={14} height={14} /></button>
                  <button className="mh-icon" title="Export"><DownloadIcon width={14} height={14} /></button>
                </div>
              </div>

              <WorldMap
                events={mapEvents}
                selected={selected}
                onSelect={handleSelect}
                scrub={scrub}
                daysBack={daysBack}
                interpolatedRisks={interpolatedRisks}
              />

              <Timeline
                value={scrub}
                onChange={setScrub}
                playing={playing}
                onPlayToggle={togglePlay}
                markers={timelineMarkers}
                now={now}
              />
            </div>

            <div className="bottom-row">
              <SensorNetwork />
              <ForecastChart />
            </div>
          </section>

          <aside className="col-right">
            <div className="right-head">
              <div className="rh-title">
                ACTIVE EVENT FEED
                {daysBack !== 0 && <span className="aef-past-indicator">{daysBack > 0 ? 'PAST DATA' : 'FORECAST'}</span>}
              </div>
              <div className="rh-meta">
                <span className="pulse-dot" />
                {filteredEvents.length} EVENTS
                <div className="rh-source">NASA EONET</div>
              </div>
            </div>

            <div className="filter-row">
              {FILTER_BTNS.map(f => (
                <button
                  key={f.k}
                  className={`fbtn ${filter === f.k ? 'on' : ''}`}
                  onClick={() => setFilter(f.k)}
                >
                  {f.label}
                </button>
              ))}
            </div>

            <div className={`event-list${expanded ? ' has-selection' : ''}`}>
              {groupedEvents.map(g => (
                <EventGroup
                  key={g.severity}
                  severity={g.severity}
                  events={g.events}
                  selected={selected}
                  expanded={expanded}
                  onSelect={handleSelect}
                  onExpand={setExpanded}
                  interpolatedRisks={interpolatedRisks}
                />
              ))}
            </div>
          </aside>
        </div>
      </div>

      <div className="vignette" />
      <div className="noise" />
    </div>
  );
}
